[options]
admin_passwd = ${ADMIN_PASS}
db_host = ${DB_HOST}
db_port = ${DB_PORT:-5432}
db_user = ${DB_USER:-odoo}
db_password = ${DB_PASSWORD}
db_name = ${DB_NAME:-odoo}
db_filter = ^%d$

addons_path = /odoo/odoo/addons,/odoo/addons

default_productivity_apps = True

logfile = /var/log/odoo/odoo.log
log_level = info

workers = ${WORKERS:-0}
max_cron_threads = ${MAX_CRON_THREADS:-2}

proxy_mode = True
longpolling_port = 8072

limit_time_real = 120
limit_time_cpu = 60

